mod_name=DynamicTreesBOP
mod_id=dtbop
mod_version=3.4.1
mod_group_id=therealeststu.dtbop
mod_authors=mangoose, Max Hyper

minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_version=21.1.97

dynamicTreesVersion=1.5.0
dynamicTreesPlusVersion=1.3.0-BETA04

versionType=stable
versionRecommended=true
updateCheckerPath=Add-ons/BOP.json

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
