mod_name=DynamicTreesBOP
mod_id=dtbop
mod_version=3.5.0-fabric-alpha
mod_group_id=therealeststu.dtbop
mod_authors=mangoose, Max Hyper

minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_version=0.155.2+26.2

dynamicTreesVersion=1.8.0-BETA03
bopVersion=26.2.0.0.26
glitchcoreVersion=26.2.0.0.0

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
