mod_name=DynamicTreesBOP
mod_id=dtbop
mod_version=3.4.1
mod_group_id=therealeststu.dtbop
mod_license=MIT
mod_credits=mangoose, Max Hyper
mod_authors=mangoose, Max Hyper
mod_description=Compatibility Mod between Dynamic trees and Biomes o' plenty
mod_url=https://www.curseforge.com/minecraft/mc-mods/dtbop
mod_issue_url=https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues
mod_update_url=https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/BOP.json?raw=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.208
loader_version_range=[1,)

# Dynamic Trees
dynamic_trees_version=1.7.2
dynamic_trees_plus_version=1.3.2

# Utilities
jade_version=15.10.5
jei_version=19.39.0.371
cc_version=1.120.0

# Addon
bop_version=BtZKRp69
terrablender_version=4.1.0.8

versionType=stable
versionRecommended=true
updateCheckerPath=Add-ons/BOP.json

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
