modLoader="javafml"
loaderVersion="[36,37)"
license="MIT"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues"

[[mods]]
modId="dtbop"
version="${file.jarVersion}"
displayName="Dynamic Trees for Biomes o' Plenty"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/BOP.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dtbop"
logoFile=""
credits="ferreusveritas"
authors="mangoose, Max Hyper"
description='''
Compatibility Mod between Dynamic trees and Biomes o' plenty
'''

[[dependencies.dtbop]]
    modId="forge"
    mandatory=true
    versionRange="[36,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbop]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbop]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbop]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.16.4-13.0.0.439,)"
    ordering="AFTER"
    side="BOTH"
