modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_url}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="${mod_update_url}"
displayURL="${mod_url}"
logoFile=""
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.dtbop]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbop]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbop]]
    modId="dynamictrees"
    type="optional"
    versionRange="[${dynamic_trees_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbop]]
    modId="dynamictreesplus"
    type="required"
    versionRange="[${dynamic_trees_plus_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbop]]
    modId="biomesoplenty"
    type="required"
    versionRange="[${bop_version},)"
    ordering="AFTER"
    side="BOTH"
