modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]] #mandatory
modId="dtbop" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Dynamic Trees for Biomes o' Plenty" #mandatory
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/BOP.json?raw=true" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/dtbop" #optional
logoFile="" #optional
credits="ferreusveritas, Nyfaria, ISNing, Groupix05" #optional
authors="mangoose, Max Hyper" #optional

description='''
Compatibility Mod between Dynamic trees and Biomes o' plenty
'''

[[dependencies.dtbop]] #optional
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbop]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbop]]
    modId="dynamictrees"
    type="required"
    versionRange="[1.5.0-BETA01,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbop]]
    modId="dynamictreesplus"
    type="optional"
    versionRange="[1.2.0-BETA1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbop]]
    modId="biomesoplenty"
    type="required"
    versionRange="[21.1.0.7,)"
    ordering="AFTER"
    side="BOTH"
